pipeline:
  publish:
    image: plugins/docker
    repo: jsoude/influxdb-collectd
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
     
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
      
  
