kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    repo: jsoude/influxdb-collectd
    tags: 
      - latest
      - 1.6.4
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  
